=== SzMartin1/WJFAOO_XMLGyak/XMLTaskWJFAOO/1.feladat/XMLSchemaWJFAOO.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!-- Egyszerű típusok definiálása -->
    <!--Jatek_nev egyszerű típusai -->
    <xs:element name="kieg_nev" type="xs:string"></xs:element>
    <xs:element name="nyelv" type="xs:string"></xs:element>
    <xs:element name="kiad_datum" type="xs:string"></xs:element>

    <!-- Szornyek egyszerű típusai -->
    <xs:element name="ero" type="xs:string"></xs:element>
    <xs:element name="menekules" type="xs:string"></xs:element>
    <xs:element name="kincs" type="xs:string"></xs:element>
    <xs:element name="szint" type="xs:string"></xs:element>
    <xs:element name="kaszt_ellen" type="xs:string"></xs:element>

    <!-- Kasztok egyszerű típusai -->
    <xs:element name="kepesseg" type="xs:string"></xs:element>
    <xs:element name="alap_tul" type="xs:string"></xs:element>
    <xs:element name="k_nehezseg" type="xs:string"></xs:element>

    <!-- Kasztok egyszerű típusai -->
    <xs:element name="rossz" type="xs:string"></xs:element>
    <xs:element name="jo" type="xs:string"></xs:element>
    <xs:element name="f_nehezseg" type="xs:string"></xs:element>

    <!-- Viseletek egyszerű típusai -->
    <xs:element name="kaszt_spec" type="xs:string"></xs:element>
    <xs:element name="fajta" type="xs:string"></xs:element>
    <xs:element name="bonusz" type="xs:string"></xs:element>
    <xs:element name="egyedi_tul" type="xs:string"></xs:element>

<!-- Attributumok definiálása -->
    <xs:attribute name="Jatek_id" type="xs:string" />
    <xs:attribute name="S_id" type="xs:string" />
    <xs:attribute name="S_J_id" type="xs:string" />
    <xs:attribute name="K_id" type="xs:string" />
    <xs:attribute name="K_J_id" type="xs:string" />
    <xs:attribute name="F_id" type="xs:string" />
    <xs:attribute name="V_id" type="xs:string" />
    <xs:attribute name="F_V_id" type="xs:string" />
    <xs:attribute name="F_J_id" type="xs:string" />
    <xs:attribute name="H_F_id" type="xs:string" />
    <xs:attribute name="H_J_id" type="xs:string" />

<!-- Összetett típusok definiálása -->
    <!-- Jatek_nev típus -->
    <xs:complexType name="Jatek_nev_tipus">
        <xs:sequence>
            <xs:element ref="kieg_nev"></xs:element>
            <xs:element ref="nyelv"></xs:element>
            <xs:element ref="kiad_datum"></xs:element>
        </xs:sequence>
        <xs:attribute ref="Jatek_id" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Szorny típus -->
    <xs:complexType name="Szorny_tipus">
        <xs:sequence>
            <xs:element ref="ero"></xs:element>
            <xs:element ref="menekules"></xs:element>
            <xs:element name="jutalom">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="kincs"></xs:element>
                        <xs:element ref="szint"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element ref="kaszt_ellen"></xs:element>
        </xs:sequence>
        <xs:attribute ref="S_id" use="required"></xs:attribute>
        <xs:attribute ref="S_J_id" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Kaszt típus -->
    <xs:complexType name="Kaszt_tipus">
        <xs:sequence>
            <xs:element ref="kepesseg"></xs:element>
            <xs:element ref="alap_tul"></xs:element>
            <xs:element ref="k_nehezseg"></xs:element>
        </xs:sequence>
        <xs:attribute ref="K_id" use="required"></xs:attribute>
        <xs:attribute ref="K_J_id" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Faj típus -->
    <xs:complexType name="Faj_tipus">
        <xs:sequence>
            <xs:element name="tulajdonsag">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="rossz"></xs:element>
                        <xs:element ref="jo"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element ref="f_nehezseg"></xs:element>
        </xs:sequence>
        <xs:attribute ref="F_id" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Viselet típus -->
    <xs:complexType name="Viselet_tipus">
        <xs:sequence>
            <xs:element ref="kaszt_spec"></xs:element>
            <xs:element ref="fajta"></xs:element>
            <xs:element ref="bonusz"></xs:element>
            <xs:element ref="egyedi_tul"></xs:element>
        </xs:sequence>
        <xs:attribute ref="V_id" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="Felszereles_tipus">
        <xs:attribute ref="F_V_id" use="required"></xs:attribute>
        <xs:attribute ref="F_J_id" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="Hovatartozas_tipus">
        <xs:attribute ref="H_F_id" use="required"></xs:attribute>
        <xs:attribute ref="H_J_id" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Maga a séma -->
    <xs:element name="Tarsasjatek">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Jatek_nev" type="Jatek_nev_tipus" maxOccurs="unbounded" />
                <xs:element name="Szorny" type="Szorny_tipus" maxOccurs="unbounded" />
                <xs:element name="Kaszt" type="Kaszt_tipus" maxOccurs="unbounded" />
                <xs:element name="Faj" type="Faj_tipus" maxOccurs="unbounded" />
                <xs:element name="Viselet" type="Viselet_tipus" maxOccurs="unbounded" />
                <xs:element name="Felszereles" type="Felszereles_tipus" maxOccurs="unbounded"/>
                <xs:element name="Hovatartozas" type="Hovatartozas_tipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <!-- Kulcsok -->
        <xs:key name="Jatek_nev_kulcs">
            <xs:selector xpath="Jatek_nev"></xs:selector>
            <xs:field xpath="@Jatek_id"></xs:field>
        </xs:key>

        <xs:key name="Szorny_kulcs">
            <xs:selector xpath="Szorny"></xs:selector>
            <xs:field xpath="@S_id"></xs:field>
        </xs:key>

        <xs:key name="Kaszt_kulcs">
            <xs:selector xpath="Kaszt"></xs:selector>
            <xs:field xpath="@K_id"></xs:field>
        </xs:key>

        <xs:key name="Faj_kulcs">
            <xs:selector xpath="Faj"></xs:selector>
            <xs:field xpath="@F_id"></xs:field>
        </xs:key>

        <xs:key name="Viselet_kulcs">
            <xs:selector xpath="Viselet"></xs:selector>
            <xs:field xpath="@V_id"></xs:field>
        </xs:key>

        <!-- Idegen kulcsok -->
        <xs:keyref name="Kaszt_idegen_kulcs" refer="Jatek_nev_kulcs">
            <xs:selector xpath="Kaszt"></xs:selector>
            <xs:field xpath="@K_J_id"></xs:field>
        </xs:keyref>

        <xs:keyref name="Faj_idegen_kulcs" refer="Faj_kulcs">
            <xs:selector xpath="Hovatartozas"></xs:selector>
            <xs:field xpath="@H_F_id"></xs:field>
        </xs:keyref>

        <xs:keyref name="Viselet_idegen_kulcs" refer="Viselet_kulcs">
            <xs:selector xpath="Felszereles"></xs:selector>
            <xs:field xpath="@F_V_id"></xs:field>
        </xs:keyref>

        <xs:keyref name="Felszereles_idegen_kulcs" refer="Jatek_nev_kulcs">
            <xs:selector xpath="Felszereles"></xs:selector>
            <xs:field xpath="@F_J_id"></xs:field>
        </xs:keyref>

        <xs:keyref name="Hovatartozas_idegen_kulcs" refer="Jatek_nev_kulcs">
            <xs:selector xpath="Hovatartozas"></xs:selector>
            <xs:field xpath="@H_J_id"></xs:field>
        </xs:keyref>

        <!-- 1:1 kapcsolat megvalósítása -->
        <xs:unique name ="unique_Szorny">
            <xs:selector xpath="Szorny"></xs:selector>
            <xs:field xpath="@S_J_id"></xs:field>
        </xs:unique>
    </xs:element>
</xs:schema>

=== SzMartin1/WJFAOO_XMLGyak/XMLTaskWJFAOO/2.feladat/DomParseWJFAOO/XML2Wjfaoo.xml
<?xml version="1.0" encoding="UTF-8"?>

<Tarsasjatek xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaWJFAOO.xsd">

    <!-- Jatekok-->
    <Jatek_nev Jatek_id="01">
        <kieg_nev>Zarándokok csatája</kieg_nev>
        <nyelv>Magyar</nyelv>
        <kiad_datum>2015.07.08.</kiad_datum>
    </Jatek_nev>

    <Jatek_nev Jatek_id="02">
        <kieg_nev>A harcos álma</kieg_nev>
        <nyelv>Magyar</nyelv>
        <kiad_datum>2017.12.01.</kiad_datum>
    </Jatek_nev>

    <Jatek_nev Jatek_id="03">
        <kieg_nev>A fáraó átka</kieg_nev>
        <nyelv>Magyar</nyelv>
        <kiad_datum>2020.01.01.</kiad_datum>
    </Jatek_nev>

    <!-- Szornyek -->
    <!-- Tavi Sejuani-->
    <Szorny S_id="01" S_J_id="01">
        <ero>Közepesen erős</ero>
        <menekules>-3 szint</menekules>
        <jutalom>
            <kincs>+10 arany</kincs>
            <szint>+5 szint</szint>
        </jutalom>
        <kaszt_ellen>Elf ellen erős</kaszt_ellen>
    </Szorny>
    <!-- Ifjú Sárkányharcos-->
    <Szorny S_id="02" S_J_id="02">
        <ero>Közepesen erős</ero>
        <menekules>-3 szint</menekules>
        <jutalom>
            <kincs>+10 arany</kincs>
            <szint>+5 szint</szint>
        </jutalom>
        <kaszt_ellen>Ork ellen erős</kaszt_ellen>
    </Szorny>
    <!-- Óriás Skorpió-->
    <Szorny S_id="03" S_J_id="03">
        <ero>Nagyon erős</ero>
        <menekules>-4 szint</menekules>
        <jutalom>
            <kincs>+20 arany</kincs>
            <szint>+7 szint</szint>
        </jutalom>
        <kaszt_ellen>Gnóm ellen erős</kaszt_ellen>
    </Szorny>

    <!-- Kasztok -->
    <!--Bárd-->
    <Kaszt K_id="01" K_J_id="01">
        <kepesseg>+1 kincslap húzás</kepesseg>
        <alap_tul>3 lapért jutalom nélküli segítségkérés</alap_tul>
        <k_nehezseg>-1 szint harcok után a szintkapásból</k_nehezseg>
    </Kaszt>
    <!--Harcos-->
    <Kaszt K_id="02" K_J_id="02">
        <kepesseg>döntetlen harcok nyerése</kepesseg>
        <alap_tul>3 lapért +1 bónusz csatában</alap_tul>
        <k_nehezseg>kétszeres sebzést szenved el</k_nehezseg>
    </Kaszt>
    <!-- Tolvaj -->
    <Kaszt K_id="03" K_J_id="03">
        <kepesseg>1 lapért hátbaszúrás: -2 bónusz</kepesseg>
        <alap_tul>1 lapért tárgylopás</alap_tul>
        <k_nehezseg>Kevesebb arany harcok után</k_nehezseg>
    </Kaszt>

    <!-- Fajok-->
    <!-- Elf -->
    <Faj F_id="01">
        <tulajdonsag>
            <rossz>-1 a meneküléshez</rossz>
            <jo>segítség esetén szintlépés</jo>
        </tulajdonsag>
        <f_nehezseg>-2 tárgycipelés</f_nehezseg>
    </Faj>
    <!-- Félszerzet -->
    <Faj F_id="02">
        <tulajdonsag>
            <rossz>-1 a meneküléshez</rossz>
            <jo>dupla árú eladás</jo>
        </tulajdonsag>
        <f_nehezseg>-2 arany harcok után</f_nehezseg>
    </Faj>
    <!-- Gnóm -->
    <Faj F_id="03">
        <tulajdonsag>
            <rossz>-1 a meneküléshez</rossz>
            <jo>szörny kijátszása magad mellett</jo>
        </tulajdonsag>
        <f_nehezseg>5 helyett csak 4 kártya</f_nehezseg>
    </Faj>

    <!-- Viseletek -->
    <!-- Celebrimbor botja -->
    <Viselet V_id="01">
        <kaszt_spec>Bárdoknak</kaszt_spec>
        <fajta>Elfeknek</fajta>
        <bonusz>+5 varázserő</bonusz>
        <egyedi_tul>+20% sebzés Szörnyek ellen</egyedi_tul>
    </Viselet>
    <!-- Jaksho sziklavértje -->
    <Viselet V_id="02">
        <kaszt_spec>Harcosoknak</kaszt_spec>
        <fajta>Félszerzeteknek</fajta>
        <bonusz>+5 életerő</bonusz>
        <egyedi_tul>Kettővel kevesebb sebzést szenved el a viselő</egyedi_tul>
    </Viselet>
    <!-- A tolvajok kesztyűje -->
    <Viselet V_id="03">
        <kaszt_spec>Tolvajoknak</kaszt_spec>
        <fajta>Gnómoknak</fajta>
        <bonusz>+5 sebesség</bonusz>
        <egyedi_tul>Minden sikeres lopás után +1 arany</egyedi_tul>
    </Viselet>

    <!-- Felszerelések (több-több kapcsolat) -->
    <Felszereles F_V_id="01" F_J_id="01"></Felszereles>

    <Felszereles F_V_id="02" F_J_id="02"></Felszereles>

    <Felszereles F_V_id="03" F_J_id="03"></Felszereles>

    <!-- Hovatartozások (több-több kapcsolat) -->
    <Hovatartozas H_F_id="01" H_J_id="01"></Hovatartozas>

    <Hovatartozas H_F_id="02" H_J_id="02"></Hovatartozas>

    <Hovatartozas H_F_id="03" H_J_id="03"></Hovatartozas>

</Tarsasjatek>
